/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IApi, IFirebaseConfig } from "./components/aloud-comments/aloud-comments";
import { IApi as IApi1, IEntry, IFirebaseConfig as IFirebaseConfig1 } from "./components/aloud-comments/aloud-comments";
export namespace Components {
    interface AloudComments {
        /**
          * API configuration. Will be `yaml.safeLoad()`  Requires either string version in HTML or Object version in JSX
         */
        "_api": string;
        /**
          * Firebase configuration. Will be `yaml.safeLoad()`  Requires either string version in HTML or Object version in JSX
         */
        "_firebase": string;
        /**
          * API configuration
         */
        "api": IApi;
        "debug": boolean;
        /**
          * Firebase configuration
         */
        "firebase": IFirebaseConfig;
    }
    interface AloudEditor {
        "firebase": IFirebaseConfig;
        "getValue": () => Promise<string>;
        /**
          * Markdown to be parsed in-and-out of the editor  Use `.getValue()` to get and update the value
         */
        "value": string;
    }
    interface AloudEntry {
        "api": IApi;
        "entry": IEntry;
        "firebase": IFirebaseConfig;
    }
    interface AloudSubentry {
        "api": IApi;
        "entry": IEntry;
        "firebase": IFirebaseConfig;
        "parent": string;
    }
}
declare global {
    interface HTMLAloudCommentsElement extends Components.AloudComments, HTMLStencilElement {
    }
    var HTMLAloudCommentsElement: {
        prototype: HTMLAloudCommentsElement;
        new (): HTMLAloudCommentsElement;
    };
    interface HTMLAloudEditorElement extends Components.AloudEditor, HTMLStencilElement {
    }
    var HTMLAloudEditorElement: {
        prototype: HTMLAloudEditorElement;
        new (): HTMLAloudEditorElement;
    };
    interface HTMLAloudEntryElement extends Components.AloudEntry, HTMLStencilElement {
    }
    var HTMLAloudEntryElement: {
        prototype: HTMLAloudEntryElement;
        new (): HTMLAloudEntryElement;
    };
    interface HTMLAloudSubentryElement extends Components.AloudSubentry, HTMLStencilElement {
    }
    var HTMLAloudSubentryElement: {
        prototype: HTMLAloudSubentryElement;
        new (): HTMLAloudSubentryElement;
    };
    interface HTMLElementTagNameMap {
        "aloud-comments": HTMLAloudCommentsElement;
        "aloud-editor": HTMLAloudEditorElement;
        "aloud-entry": HTMLAloudEntryElement;
        "aloud-subentry": HTMLAloudSubentryElement;
    }
}
declare namespace LocalJSX {
    interface AloudComments {
        /**
          * API configuration. Will be `yaml.safeLoad()`  Requires either string version in HTML or Object version in JSX
         */
        "_api"?: string;
        /**
          * Firebase configuration. Will be `yaml.safeLoad()`  Requires either string version in HTML or Object version in JSX
         */
        "_firebase"?: string;
        /**
          * API configuration
         */
        "api": IApi;
        "debug"?: boolean;
        /**
          * Firebase configuration
         */
        "firebase": IFirebaseConfig;
    }
    interface AloudEditor {
        "firebase": IFirebaseConfig;
        /**
          * Markdown to be parsed in-and-out of the editor  Use `.getValue()` to get and update the value
         */
        "value"?: string;
    }
    interface AloudEntry {
        "api": IApi;
        "entry": IEntry;
        "firebase": IFirebaseConfig;
    }
    interface AloudSubentry {
        "api": IApi;
        "entry": IEntry;
        "firebase": IFirebaseConfig;
        "parent": string;
    }
    interface IntrinsicElements {
        "aloud-comments": AloudComments;
        "aloud-editor": AloudEditor;
        "aloud-entry": AloudEntry;
        "aloud-subentry": AloudSubentry;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "aloud-comments": LocalJSX.AloudComments & JSXBase.HTMLAttributes<HTMLAloudCommentsElement>;
            "aloud-editor": LocalJSX.AloudEditor & JSXBase.HTMLAttributes<HTMLAloudEditorElement>;
            "aloud-entry": LocalJSX.AloudEntry & JSXBase.HTMLAttributes<HTMLAloudEntryElement>;
            "aloud-subentry": LocalJSX.AloudSubentry & JSXBase.HTMLAttributes<HTMLAloudSubentryElement>;
        }
    }
}
